name: 'Testmerge Worker'

concurrency:
  group: testmerge

on:
  workflow_dispatch:

env:
  BASE_BRANCH: master220
  TESTMERGE_BRANCH: testmerge
  REQUIRED_LABEL: testmerge

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests with required label and check for merge conflicts
        id: get_labeled_prs
        uses: actions/github-script@v7
        with:
          script: |
            const label_needed = '${{ env.REQUIRED_LABEL }}';
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });
            const labeledPRs = [];
            const sortedPRsASC = pullRequests.sort((a, b) => a.created_at.localeCompare(b.created_at));
            for (const pr of sortedPRsASC) {
              if (pr.labels.some(label => label.name === label_needed)) {
                console.log(`PR ${pr.title}`);

                const { data: prInfo } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number
                });

                if (prInfo.mergeable) {
                  labeledPRs.push({
                    number: pr.number,
                    title: pr.title
                  });
                }
              }
            }
            const prDetails = JSON.stringify(labeledPRs);
            console.log(`Pull Requests with the label "${label_needed}" and no merge conflicts:\n${prDetails}`);
            if (prDetails.length == 0) {
              core.setFailed(`No pull requests with the label "${label_needed}" and no merge conflicts found.`);
            }
            core.setOutput('labeled_pr_details', prDetails);

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ env.BASE_BRANCH }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'
          cache: 'pip'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: ./tgui/yarn.lock

      - name: Install python packages
        run: |
          pip3 install -r tools/requirements.txt
          pip3 install GitPython

      - name: Iterate over PRs and perform actions
        id: prepare_testmerge_branch
        run: |
          set -e

          # Define the color functions
          red() {
            echo -e "\033[31m$1\033[0m"
          }

          green() {
            echo -e "\033[32m$1\033[0m"
          }

          yellow() {
            echo -e "\033[33m$1\033[0m"
          }

          git config --local user.email "action@github.com"
          git config --local user.name "Testmerge Worker"
          git switch ${{ env.TESTMERGE_BRANCH }} || git switch -c ${{ env.TESTMERGE_BRANCH }}
          git reset --hard ${{ env.BASE_BRANCH }}

          ./tools/hooks/install.sh
          ./tgui/bin/tgui --install-git-hooks

          MERGED_PRS=()

          # Print debug information
          echo "PR details JSON:"
          echo '${{ steps.get_labeled_prs.outputs.labeled_pr_details }}'

          echo '${{ steps.get_labeled_prs.outputs.labeled_pr_details }}' | jq -c '.[]' | while read -r PR_DETAIL; do
            PR_NUMBER=$(echo "$PR_DETAIL" | jq -r '.number')
            PR_TITLE=$(echo "$PR_DETAIL" | jq -r '.title')
            git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
            PR_LAST_COMMIT=$(git rev-parse --short pr-$PR_NUMBER | head -c 7)
            PR_STRING="$PR_TITLE (#$PR_NUMBER) [$PR_LAST_COMMIT]"
            echo "::group::$PR_STRING"
            echo "Preparing..."

            # Check for merge conflicts
            git merge --no-commit --no-ff pr-$PR_NUMBER || true
            CONFLICTS=$(git ls-files -u | wc -l)
            if [ "$CONFLICTS" -gt 0 ] ; then
              echo "::endgroup::"
              echo "$(red "$PR_STRING: There is a merge conflict. Skipping!")"
              git merge --abort
              continue
            fi
            git merge --abort

            git merge --squash pr-$PR_NUMBER
            git commit -m "$PR_TITLE (#$PR_NUMBER) [testmerge][$PR_LAST_COMMIT]"

            # Perform your git actions here, for example:
            echo "::endgroup::"
            echo "$(green "$PR_STRING:  Successfully merged!")"
            MERGED_PRS+=("$PR_NUMBER")
          done

          # Generate changelog
          python3 tools/changelog/gen_changelog.py
          git add html/changelogs/archive/\*.yml
          CHANGES=$(git diff --name-only --cached | wc -l)
          if [ "$CHANGES" -gt 0 ] ; then
            git config --local user.email "action@github.com"
            git config --local user.name "Changelog Generation"
            git commit -m "Automatic changelog generation"
          fi

          git push -f origin ${{ env.TESTMERGE_BRANCH }}

          # Output the list of merged PRs
          echo "merged_prs=${MERGED_PRS[*]}" >> $GITHUB_OUTPUT

      - name: Comment on merged PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const mergedPRs = '${{ steps.prepare_testmerge_branch.outputs.merged_prs }}'.split(' ');
            for (const prNumber of mergedPRs) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(prNumber),
                body: 'Данный PR был добавлен в ветку "${{ env.TESTMERGE_BRANCH }}" для тестов. Он попадёт на сервер после деплоя.'
              });
              console.log(`Commented on PR #${prNumber}`);
            }
